# Generated by Django 5.1.3 on 2024-12-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.CharField(max_length=200, unique=True)),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "photo_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "auth_date",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
